const music=document.getElementById('bgMusic');const playBtn=document.getElementById('playBtn');const volumeBar=document.getElementById('volumeBar');const themeBtn=document.getElementById('themeBtn');music.loop=true;music.volume=0.8;volumeBar.value=0.8;
function togglePlay(){if(music.paused){music.play().catch(()=>toast('Dale play para activar sonido'));playBtn.textContent='⏸️';}else{music.pause();playBtn.textContent='▶️';}}
function togglePlayer(){document.getElementById('musicPlayer').classList.toggle('min');const arrow=document.querySelector('.player-header span:last-child');arrow.textContent=document.getElementById('musicPlayer').classList.contains('min')?'▲':'▼';}
function prevSong(){music.currentTime=0;toast('Reiniciando')}function nextSong(){toast('Solo 1 canción')}volumeBar.oninput=()=>music.volume=volumeBar.value;
if(themeBtn){themeBtn.onclick=()=>{document.body.classList.toggle('light');themeBtn.textContent=document.body.classList.contains('light')?'☀️':'🌙';}}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='tiendaScreen')renderProductos();}

const productos=[{id:1,nom:"Bot VIP WhatsApp",marca:"For Three",precio:25,img:"bot-vip.jpg",desc:["Respuesta automática 24/7","Menú interactivo","Soporte incluido"]},{id:2,nom:"Activación Netflix",marca:"Streaming",precio:18,img:"bot-vip.jpg",desc:["1 mes full","4 pantallas","Garantía 30 días"]}];
const cupones={"F3DIEZ":0.1};const pagos={yape:{num:"999888777"},bcp:{cci:"002123456789012345"},prex:{num:"912345678"},paypal:"https://paypal.me/tuusuario"};
let currentProduct=null;let activeCoupon=null;

function renderProductos(){document.getElementById('productos').innerHTML=productos.map(p=>`<div class="card" onclick="verProducto(${p.id})"><img src="${p.img}"><h3>${p.nom}</h3><div class="precio">S/ ${p.precio}.00</div></div>`).join('');}
function verProducto(id){currentProduct=productos.find(p=>p.id===id);document.getElementById('pImg').src=currentProduct.img;document.getElementById('pMarca').textContent=currentProduct.marca;document.getElementById('pNom').textContent=currentProduct.nom;document.getElementById('pPrecio').textContent=`S/ ${currentProduct.precio}.00`;document.getElementById('pDesc').innerHTML=currentProduct.desc.map(d=>`<li>✓ ${d}</li>`).join('');document.getElementById('comprarBtn').onclick=abrirPago;show('productoScreen');}

function abrirPago(){document.getElementById('pagoModal').classList.add('active');updateMontos();}
function cerrarPago(){document.getElementById('pagoModal').classList.remove('active');}
function selectPayment(t,ev){document.querySelectorAll('.payment-tab,.payment-content').forEach(e=>e.classList.remove('active'));ev.target.classList.add('active');document.getElementById(t+'Content').classList.add('active');}
function applyCoupon(){const code=document.getElementById('couponCode').value.toUpperCase();if(cupones[code]){activeCoupon=cupones[code];document.getElementById('couponText').textContent=`${code} -10% aplicado`;document.getElementById('couponInput').style.display='none';document.getElementById('couponApplied').style.display='flex';updateMontos();toast('Cupón aplicado!');}else toast('Cupón inválido');}
function removeCoupon(){activeCoupon=null;document.getElementById('couponInput').style.display='flex';document.getElementById('couponApplied').style.display='none';document.getElementById('couponCode').value='';updateMontos();}
function updateMontos(){let precio=currentProduct.precio;if(activeCoupon)precio=precio*(1-activeCoupon);const usd=(precio/3.7).toFixed(2);['montoYape','montoTarjeta','montoPrex'].forEach(id=>document.getElementById(id).textContent=`S/ ${precio.toFixed(2)}`);document.getElementById('montoPaypal').textContent=`$${usd} USD`;document.getElementById('paypalLink').href=`${pagos.paypal}/${usd}`;document.getElementById('yapeNum').textContent=pagos.yape.num;document.getElementById('bcpCci').textContent=pagos.bcp.cci;document.getElementById('prexNum').textContent=pagos.prex.num;}
document.getElementById('wspBtn').onclick=()=>{const precio=activeCoupon?currentProduct.precio*(1-activeCoupon):currentProduct.precio;const msg=`Hola! Comprobante de ${currentProduct.nom} - S/ ${precio.toFixed(2)}`;window.open(`https://wa.me/51999888777?text=${encodeURIComponent(msg)}`,'_blank');};
function copyText(txt){navigator.clipboard.writeText(txt);toast('Copiado!')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000);}
window.addEventListener('load',()=>{show('inicioScreen');});