const TU_NUMERO_WSP = '51936994155'; // <-- CAMBIA TU NUMERO AQUI
const REDIR_WSP = `https://wa.me/${TU_NUMERO_WSP}`;
const state = {tab:'todos',theme:localStorage.getItem('f3_theme')||'dark',descuentoAplicado:{code:null,percent:0},metodoPago:'yape',productoSeleccionado:null};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const PRODUCTOS=[{id:1,cat:'bot',tag:'BOT',marca:'For Three',nom:'Bot VIP 30 días',precio:15,img:'https://i.ibb.co/3y0p0sP/bot-vip.jpg',desc:['Acceso VIP completo','Sin límites de uso','Soporte 24/7']},{id:2,cat:'bot',tag:'BOT',marca:'For Three',nom:'Bot Premium 7 días',precio:5,img:'https://i.ibb.co/3y0p0sP/bot-vip.jpg',desc:['Acceso Premium','Uso ilimitado','Soporte rápido']},{id:3,cat:'serv',tag:'SERV',marca:'For Three',nom:'Activación Yape',precio:3,img:'https://i.ibb.co/3y0p0sP/bot-vip.jpg',desc:['Activación inmediata','100% seguro']},{id:4,cat:'serv',tag:'SERV',marca:'For Three',nom:'Recarga BCP',precio:2,img:'https://i.ibb.co/3y0p0sP/bot-vip.jpg',desc:['Recarga inmediata','Sin comisión']}];
const CUPONES={F3DIEZ:10,F3CINCO:5};const CUENTAS={yape:{num:'936994155',titular:'For Three'},bank:{cci:'00219100234567890123',cuenta:'191-23456789-0-12',titular:'For Three'},prex:{num:'948572136',titular:'For Three'},paypal:{link:'https://paypal.me/ForThree',usd:0.28}};
function init(){aplicarTheme();$('#themeBtn').onclick=toggleDark;renderSubnav();resetFiltro();show('inicioScreen');}
function aplicarTheme(){document.body.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀️':'🌙';}
function toggleDark(){state.theme=state.theme==='light'?'dark':'light';localStorage.setItem('f3_theme',state.theme);aplicarTheme();}
function renderSubnav(){$('#subnav').innerHTML=`<button data-tab="todos" class="active">TODOS</button><button data-tab="bot">BOT</button><button data-tab="serv">SERVICIOS</button>`;$$('.subnav button').forEach(b=>b.onclick=()=>{$$('.subnav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tab=b.dataset.tab;render();});}
function resetFiltro(){state.tab='todos';$$('.subnav button').forEach(x=>x.classList.remove('active'));$('.subnav button[data-tab="todos"]').classList.add('active');render();}
function show(p){$$('.screen').forEach(s=>s.classList.remove('active'));$(`#${p}`).classList.add('active');}
function render(){const grid=$('#productos');let lista=PRODUCTOS.filter(p=>state.tab==='todos'||p.cat===state.tab);grid.innerHTML=lista.map(p=>`<div class="card" onclick="verProducto(${p.id})"><img src="${p.img}" loading="lazy"><div class="card-body"><div class="tag">${p.tag}</div><div class="marca">${p.marca}</div><b>${p.nom}</b><div class="precio">S/ ${p.precio.toFixed(2)}</div><button class="btn" onclick="event.stopPropagation();comprar(${p.id})">Contratar</button></div></div>`).join('');}
function verProducto(id){const p=PRODUCTOS.find(x=>x.id===id);state.productoSeleccionado=p;$('#pImg').src=p.img;$('#pMarca').textContent=p.marca;$('#pNom').textContent=p.nom;$('#pPrecio').textContent=`S/ ${p.precio.toFixed(2)}`;$('#pDesc').innerHTML=p.desc.map(d=>`<li>${d}</li>`).join('');$('#comprarBtn').onclick=()=>abrirPago();show('productoScreen');}
function comprar(id){state.productoSeleccionado=PRODUCTOS.find(x=>x.id===id);abrirPago();}
function abrirPago(){const p=state.productoSeleccionado;$('#serviceCard').innerHTML=`<img src="${p.img}"><div class="service-info"><b>${p.nom}</b><span>${p.marca}</span></div><div class="service-price">S/ ${p.precio.toFixed(2)}</div>`;$('#yapeNum').textContent=CUENTAS.yape.num;$('#yapeName').textContent=CUENTAS.yape.titular;$('#bcpCci').textContent=CUENTAS.bank.cci;$('#bcpCuenta').textContent=CUENTAS.bank.cuenta;$('#bcpNombre').textContent=CUENTAS.bank.titular;$('#prexNum').textContent=CUENTAS.prex.num;$('#prexName').textContent=CUENTAS.prex.titular;$('#paypalLink').href=CUENTAS.paypal.link;state.descuentoAplicado={code:null,percent:0};$('#couponCode').value='';$('#couponApplied').style.display='none';$('#couponInput').style.display='flex';selectPayment('yape');$('#pagoModal').classList.add('active');actualizarMontos();}
function cerrarPago(){$('#pagoModal').classList.remove('active');}
function applyCoupon(){const code=$('#couponCode').value.trim().toUpperCase();if(!CUPONES[code])return toast('Cupón inválido',true);state.descuentoAplicado={code,percent:CUPONES[code]};$('#couponText').textContent=`${code} -${CUPONES[code]}%`;$('#couponInput').style.display='none';$('#couponApplied').style.display='flex';actualizarMontos();toast(`Cupón ${code} aplicado`);}
function removeCoupon(){state.descuentoAplicado={code:null,percent:0};$('#couponInput').style.display='flex';$('#couponApplied').style.display='none';actualizarMontos();}
function getPrecioFinal(){const p=state.productoSeleccionado.precio;const d=state.descuentoAplicado.percent;return d?p*(1-d/100):p;}
function actualizarMontos(){const precio=getPrecioFinal();const usd=(precio*CUENTAS.paypal.usd).toFixed(2);$('#montoYape').textContent=`S/ ${precio.toFixed(2)}`;$('#montoTarjeta').textContent=`S/ ${precio.toFixed(2)}`;$('#montoPrex').textContent=`S/ ${precio.toFixed(2)}`;$('#montoPaypal').innerHTML=`$${usd} USD <small>≈ S/ ${precio.toFixed(2)}</small>`;}
function selectPayment(tab,e){state.metodoPago=tab;$$('.payment-tab').forEach(b=>b.classList.remove('active'));if(e)e.target.classList.add('active');$$('.payment-content').forEach(c=>c.classList.remove('active'));$(`#${tab}Content`).classList.add('active');actualizarMontos();}
function copyText(txt){navigator.clipboard.writeText(txt);toast('Copiado ✅');}
function guardarVenta(){const precioFinal=getPrecioFinal();const venta={id:'F3-'+Date.now(),producto:state.productoSeleccionado.nom,precio_soles:precioFinal,metodo:state.metodoPago,cupon:state.descuentoAplicado.code||'Ninguno',fecha:new Date().toLocaleString('es-PE',{timeZone:'America/Lima'}),estado:'PENDIENTE'};const msgBot=`🚨 *NUEVA VENTA PENDIENTE* 🚨\n\n*ID:* ${venta.id}\n*Producto:* ${venta.producto}\n*Monto:* S/ ${venta.precio_soles.toFixed(2)}\n*Método:* ${venta.metodo}\n*COPIA ESTO Y ENVIALO AL BOT:*\n\`\`json\n${JSON.stringify(venta,null,2)}\n\`\``;const msgCliente=`Hola For Three! 👋\n\nYa pagué S/ ${precioFinal.toFixed(2)} por:\n*${venta.producto}*\nMetodo: ${venta.metodo}\nID: ${venta.id}\n\nAdjunto mi comprobante 📸`;window.open(`${REDIR_WSP}?text=${encodeURIComponent(msgBot)}`,'_blank');setTimeout(()=>{window.open(`${REDIR_WSP}?text=${encodeURIComponent(msgCliente)}`,'_blank');},1000);cerrarPago();toast('Pedido enviado al Bot ✅');}
$('#wspBtn').onclick=guardarVenta;
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');setTimeout(()=>t.classList.remove('show'),3000);}
window.verProducto=verProducto;window.comprar=comprar;window.abrirPago=abrirPago;window.cerrarPago=cerrarPago;window.applyCoupon=applyCoupon;window.removeCoupon=removeCoupon;window.selectPayment=selectPayment;window.copyText=copyText;window.show=show;
init();